import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }

[window]
startup_mode = "Maximized"

[colors]
cursor = { text = "#000000", cursor = "#ffffff" }
